server:
  port: 8080

spring:
  application:
    name: social-media-service
  jackson:
    time-zone: UTC
  datasource:
    url: ${DATABASE_URL:}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

twitter:
  api:
    base-url: https://api.twitterapi.io
    key: ${TWITTER_API_KEY:}

logging:
  level:
    root: INFO
    com.socialmedia: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
